export const Contacts = () => {
  return (
    <div>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum tenetur eius commodi maxime assumenda voluptatibus aliquam autem consequatur quia obcaecati expedita quas reprehenderit exercitationem corporis repudiandae labore, excepturi officia rerum!</p>
    </div>
  )
}